POST http://localhost:3000/films
content-type: application/json

{
  "title": "Fight Club",
  "isFavorite": 1,
  "rating": 5,
  "watchDate": "2024-04-01",
  "UserId": 1
}

PUT http://localhost:3000/films/1
content-type: application/json

{
  "title": "fizione pulp!",
  "isFavorite": 1,
  "rating": 5,
  "watchDate": "2024-03-10",
  "UserId": 1
}